Repository dusk-network/dusk-zerocaf, pull requests merged in 2019-07, with the labels that each got.

#34 Implementation for Add and double and it's dependent methods.
  src/backend/u64/field.rs
  src/backend/u64/scalar.rs
  src/constants.rs
  src/edwards.rs
  src/scalar.rs
  tools/src/main.rs
  tools/tonelli.py
Labels: enhancement

#35 [WIP] Compression, Decompression & other features for Edwards.
  src/backend/u64/field.rs
  src/edwards.rs
Labels: enhancement, research

#40 Add badages and Zerocaf logo.
  src/lib.rs
Labels: Documentation

#41 Finnish docs. Wait review.
  src/backend/mod.rs
  src/constants.rs
  src/edwards.rs
  src/field.rs
  src/lib.rs
  src/montgomery.rs
  src/scalar.rs
Labels: Documentation

#42 Add Security & Features block on docs
  src/lib.rs
Labels: Documentation

#43 Implement EdwardsPoint crafting on the tooling
  tools/src/main.rs
Labels: enhancement, testing

#46 Fix some doc errors.
  src/backend/mod.rs
  src/backend/u64/constants.rs
  src/backend/u64/field.rs
  src/backend/u64/mod.rs
  src/backend/u64/scalar.rs
  src/constants.rs
  src/edwards.rs
  src/lib.rs
  src/montgomery.rs
Labels: Documentation

#52 Add examples and examples folder.
  examples/basic_ops.rs
  src/lib.rs
  tools/Phase1_Rust_logs
  tools/Phase1_py_logs
  tools/phase2_py_logs
  tools/phase2_rust_logs
Labels: Documentation

#53 Allow compilation.
  Cargo.toml
Labels: Documentation

#54 Implement docs for field and scalar mods.
  src/backend/u64/field.rs
  src/backend/u64/scalar.rs
  src/field.rs
  src/scalar.rs
Labels: Documentation, enhancement

#56 Implement `ProjectivePoint` and improved docs.
  README.md
  benchmarks/dusk_benchmarks.rs
  examples/basic_ops.rs
  src/backend/u64/field.rs
  src/backend/u64/scalar.rs
  src/edwards.rs
  src/field.rs
  src/lib.rs
  src/scalar.rs
  src/traits.rs
Labels: Documentation, enhancement, review needed

#64 Point Generation implementation
  Cargo.toml
  benchmarks/dusk_benchmarks.rs
  src/backend/u64/field.rs
  src/backend/u64/scalar.rs
  src/edwards.rs
  src/field.rs
  src/traits.rs
Labels: end_user_utility, review needed, speed_improvement

#67 Implement Twisted Edwards Affine Coordinates
  README.md
  src/backend/u64/field.rs
  src/backend/u64/scalar.rs
  src/edwards.rs
Labels: enhancement, review needed

#68 Files transfer
  sage_codes/Point computation 
  sage_codes/Safe Curve code
  src/backend/mod.rs
  src/backend/u64/constants.rs
  src/backend/u64/field.rs
  src/edwards.rs
Labels: documentation, review needed

#69 Implement Point Compression/Decompression for Twisted Edwards Coordinates.
  src/backend/u64/field.rs
  src/edwards.rs
Labels: documentation, end_user_utility, enhancement, review needed, speed_improvement

#71 Merge request for past and current commits.
  sage_codes/Safe Curve code
  src/backend/mod.rs
  src/backend/u64/field.rs
  src/backend/u64/mod.rs
Labels: documentation, research

#72 Last doc updates & benches for bumping to v0.2.0
  benchmarks/dusk_benchmarks.rs
  src/backend/u64/field.rs
  src/edwards.rs
  src/field.rs
  src/scalar.rs
Labels: documentation, end_user_utility, review needed, speed_improvement
